version: "3.9"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: dotnetclimateweather
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  minha-aplicacao:
    build:
      context: ./dotnet-climate-weather # Substitua pelo diretório da sua aplicação
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sql-server
